version: '3.19'
services:
  nodeapp:
    build: .
    image: imanhpr/simplenodecrud:latest
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - database
    
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB : appdb